---
- name: Include variables
  include_tasks: variables.yml

- name: Install required version of mysql
  include_tasks: "{{ ansible_os_family }}-mysql-install.yml"
  
- name: Enable and start mysql
  systemd:
    name: mysql
    state: started
    enabled: true