---
- name: load variables based on OS type
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - 'vars/{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
      - 'vars/{{ ansible_os_family }}.yml'
      skip: true

- name: Define packages
  set_fact:
    mysql_packages: "{{ __mysql_packages | list }}"
  when: mysql_packages is not defined

- name: Set mysql daemon
  set_fact:
    mysql_daemon: "{{ __mysql_daemon }}"
  when: mysql_daemon is not defined 