---
- name: Verify
  hosts: all
  gather_facts: true 
  tasks:
    - name: Get information on state
      ansible.builtin.service_facts:

    - name: Set fact for Debian
      set_fact:
        mysql_status: "{{ ansible_facts.services['mariadb.service']['state'] }}"
      when: ansible_distribution == "Debian"

    - name: Set fact for ubuntu
      set_fact:
        mysql_status: "{{ ansible_facts.services['mysql']['state'] }}"
      when: ansible_distribution == "Ubuntu"

    - name: Test mysql service is running
      debug:
        var: mysql_status
      failed_when: "'stopped' in mysql_status"
