---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Gather info 
      ansible.builtin.service_facts:
    - name: Test mysql service is running
      debug:
        var: ansible_facts.services['mysql']
      failed_when: "'stopped' in ansible_facts.services['mysql']['state'] "

